-- MySQL Script generated by MySQL Workbench
-- 07/05/14 00:30:04
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema UltraNegocio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UltraNegocio` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `UltraNegocio` ;

-- -----------------------------------------------------
-- Table `UltraNegocio`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UltraNegocio`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(245) NULL,
  `email` VARCHAR(245) NULL,
  `senha` VARCHAR(245) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  `email_confirmado` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UltraNegocio`.`anuncios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UltraNegocio`.`anuncios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(245) NULL,
  `descricao` LONGBLOB NULL,
  `preco` FLOAT NULL,
  `criado` DATETIME NULL,
  `modificado` VARCHAR(45) NULL,
  `excluido` TINYINT(1) NULL DEFAULT 0,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_anuncios_usuarios1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_anuncios_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `UltraNegocio`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UltraNegocio`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UltraNegocio`.`imagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL,
  `titulo` VARCHAR(250) NULL,
  `description` TEXT NULL,
  `url` VARCHAR(250) NULL,
  `anuncio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_imagens_anuncios_idx` (`anuncio_id` ASC),
  CONSTRAINT `fk_imagens_anuncios`
    FOREIGN KEY (`anuncio_id`)
    REFERENCES `UltraNegocio`.`anuncios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UltraNegocio`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UltraNegocio`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(245) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UltraNegocio`.`anuncious_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UltraNegocio`.`anuncious_tag` (
  `tag_id` INT NOT NULL,
  `anuncio_id` INT NOT NULL,
  PRIMARY KEY (`tag_id`, `anuncio_id`),
  INDEX `fk_tags_has_anuncios_anuncios1_idx` (`anuncio_id` ASC),
  INDEX `fk_tags_has_anuncios_tags1_idx` (`tag_id` ASC),
  CONSTRAINT `fk_tags_has_anuncios_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `UltraNegocio`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_has_anuncios_anuncios1`
    FOREIGN KEY (`anuncio_id`)
    REFERENCES `UltraNegocio`.`anuncios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
